get http://localhost:3003/api/blogs
Content-type: application/application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsc2Euc2FybGluIiwiaWQiOiI1ZGZjZDVjNzdmZjE1ZjRjNjRhNTU5ZmYiLCJpYXQiOjE1Nzg5MzgzMTh9.S2DyGZr9EHD0qFpg8nC7bYZqmUeOohrNNSTVZwRbmv4