services:
  app:
    image: todo-front-dev
    build:
      context: . 
      dockerfile: dev.Dockerfile 
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    container_name: todo-front-dev
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000
      PORT: 8080