services:
  app:
    image: todo-front-dev
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: todo-front
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000
      PORT: 8080